"""
Semantic analysis produced by the SOC Agent.
Unlike SOCReport, this model is independent from presentation concerns.
It captures the reasoning generated by the agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .base import BaseModel
from .evidence import EvidenceItem


@dataclass(slots=True)
class AgentAnalysis(BaseModel):
    """
    This object is later transformed into a SOCReport by the
    ReportBuilder.
    """

    executive_summary: str

    event_overview: str

    analyst_notes: str = ""

    evidence: list[EvidenceItem] = field(default_factory=list)

    reasoning: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "executive_summary": self.executive_summary,
            "event_overview": self.event_overview,
            "analyst_notes": self.analyst_notes,
            "reasoning": self.reasoning,
            "evidence": [evidence.to_dict() for evidence in self.evidence],
        }

    @property
    def evidence_count(self) -> int:
        return len(self.evidence)
