"""
Structured output generated by the SOC Agent.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from .evidence import EvidenceItem


class AgentAnalysis(BaseModel):
    """
    This object is later transformed into a SOCReport by the
    ReportBuilder.
    """

    executive_summary: str = Field(
        description="Short human-readable summary of the security event."
    )

    event_overview: str = Field(
        description="Technical explanation of the observed activity."
    )

    analyst_notes: str = Field(
        default="",
        description="Additional observations from the SOC analyst perspective.",
    )

    evidence: list[EvidenceItem] = Field(
        default_factory=list, description="Evidence supporting the analysis."
    )

    reasoning: list[str] = Field(
        default_factory=list, description="Explainable reasoning behind the conclusion."
    )

    @property
    def evidence_count(self) -> int:
        return len(self.evidence)

    def to_dict(self) -> dict:
        return self.model_dump()
