"""
Domain model representing the final SOC analysis report generated by LogGuard.
The SOCReport object is format-independent. Renderers are responsible for
transforming it into JSON, Markdown or any other presentation format.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from .base import BaseModel
from .evidence import EvidenceItem
from .recommendation import Recommendation


class ReportSeverity(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReportConfidence(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


@dataclass(slots=True)
class SOCReport(BaseModel):
    title: str

    executive_summary: str

    event_overview: str

    severity: ReportSeverity

    confidence: ReportConfidence

    evidence: list[EvidenceItem] = field(default_factory=list)

    recommendations: list[Recommendation] = field(default_factory=list)

    analyst_notes: str = ""

    generated_at: str | None = None

    def to_dict(self) -> dict:

        return {
            "title": self.title,
            "executive_summary": self.executive_summary,
            "event_overview": self.event_overview,
            "severity": self.severity.value,
            "confidence": self.confidence.value,
            "evidence": [item.to_dict() for item in self.evidence],
            "recommendations": [
                recommendation.to_dict() for recommendation in self.recommendations
            ],
            "analyst_notes": self.analyst_notes,
            "generated_at": self.generated_at,
        }

    @property
    def evidence_count(self) -> int:

        return len(self.evidence)

    @property
    def recommendation_count(self) -> int:
        return len(self.recommendations)

    @property
    def has_critical_recommendations(self) -> bool:
        return any(
            recommendation.is_critical for recommendation in self.recommendations
        )

    @property
    def requires_attention(self) -> bool:
        """
        Quick helper used by future integrations.
        """

        return self.severity in (
            ReportSeverity.HIGH,
            ReportSeverity.CRITICAL,
        )
